[tool.pytest.ini_options]
python_functions = "test_*"
python_files = "test_*.py"
asyncio_mode = "auto"
testpaths = "tests"
pythonpath = ["."]

[tool.ruff]
line-length = 80
exclude = ["venv"]
extend-ignore = [
    "F821",  # Disable checks for annotated SQLAlchemy relations 
]
