[default]
    [default.oauth.google]
    client_id = "xxx.apps.googleusercontent.com"
    client_secret = "secret"
    redirect_uri = "http://localhost:5173"
    enabled = true

    [default.database]
    endpoint = "postgresql+asyncpg://user:password@localhost:5432/database"

    [default.mailgun]
    endpoint = "https://api.eu.mailgun.net/v3/mail.hikka.io/messages"
    token = "token"

    [default.meilisearch]
    url = "http://127.0.0.1:8800"
    api_key = "xyz"

    [default.backend]
    origins = [
        "http://localhost:8000",
        "http://localhost:3000",
        "http://localhost:5173",
        "https://hikka.io",
    ]

[testing]
    [testing.database]
    endpoint = "postgresql+asyncpg://user:password@localhost:5432/database-tests"

    [testing.oauth.google]
    client_id = "xxx.apps.googleusercontent.com"
    client_secret = "secret"
    redirect_uri = "http://example.com/oauth/google"
    enabled = true
